//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filedb
    {
        public int FileId { get; set; }
        public byte[] Filecontent { get; set; }
        public Nullable<System.DateTime> Datecreated { get; set; }
        public string FileName { get; set; }
        public int Size { get; set; }
        public string ContentType { get; set; }
        public string Extension { get; set; }

        public Filedb()
        {
            this.Datecreated= DateTime.UtcNow;
        }
    }
}
